[programs.localnet]
solana_twitter = "4dL4d4sRCSG2esqxaaAKyfrZDP2Qis8X7peQHw9TtwmE"

[programs.devnet]
solana_twitter = "4dL4d4sRCSG2esqxaaAKyfrZDP2Qis8X7peQHw9TtwmE"

[programs.mainnet]
solana_twitter = "4dL4d4sRCSG2esqxaaAKyfrZDP2Qis8X7peQHw9TtwmE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/bstudent/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
copy-idl = "mkdir -p app/src/idl && cp target/idl/solana_twitter.json app/src/idl/solana_twitter.json"
